#!/bin/bash
set -e 

# Install Terminator
if ! [ -x "$(command -v terminator)" ]; then
    sudo apt install -y terminator
fi

# Install Google Chrome
if ! [ -x "$(command -v google-chrome)" ]; then
    curl -fsSLO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb | sudo -E bash - &&\
    sudo apt install -y ./google-chrome-stable_current_amd64.deb
    rm google-chrome-stable_current_amd64.deb
fi

# Install Neofetch
if ! [ -x "$(command -v neofetch)" ]; then
    sudo apt install -y neofetch
fi

# Install curl
if ! [ -x "$(command -v curl)" ]; then
    sudo apt install -y curl
fi

# Install C/C++ compilers; needed for C/C++ LSP in Nvim
if ! [ -x "$(command -v gcc)" ]; then
    sudo apt install -y build-essential
fi

# Install ripgrep; needed for Telescope in Nvim
if ! [ -x "$(command -v rg)" ]; then
    sudo apt install -y ripgrep
fi

# Install Node.js; needed for certain LSPs used in Nvim
if ! [ -x "$(command -v npm)" ]; then
    curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
    sudo apt-get install -y nodejs
fi

# Install Nvim
if ! [ -x "$(command -v nvim)" ]; then
    curl -fsSLO https://github.com/neovim/neovim/releases/download/v0.8.3/nvim-linux64.deb | sudo -E bash - &&\
    sudo apt install -y ./nvim-linux64.deb
    rm nvim-linux64.deb
fi

# Install Packer.nvim
if ! [ -d "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim" ]; then
    git clone --depth 1 https://github.com/wbthomason/packer.nvim\
     $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim
fi

# Copy Nvim configuration to .config/
if [ -d "./nvim" ]; then 
    cp -r ./nvim $HOME/.config
fi

# Run PackerSync in Nvim and suppress all messages
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync' &>/dev/null

# Install Rust
if ! [ -x "$(command -v cargo)" ]; then
    curl https://sh.rustup.rs -sSf | sh
fi
