#!/bin/bash
set -e 

# Install curl
if ! [ -x "$(command -v curl)" ]; then
    sudo apt install -y curl
fi

# Install C/C++ compilers
if ! [ -x "$(command -v gcc)" ]; then
    sudo apt install -y build-essential
fi

# Install ripgrep
if ! [ -x "$(command -v rg)" ]; then
    sudo apt install -y ripgrep
fi

# Install Node.js
if ! [ -x "$(command -v npm)" ]; then
    curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
    sudo apt-get install -y nodejs
fi

# Install Nvim
if ! [ -x "$(command -v nvim)" ]; then
    curl -fsSLO https://github.com/neovim/neovim/releases/download/v0.8.3/nvim-linux64.deb | sudo -E bash - &&\
    sudo apt install -y ./nvim-linux64.deb
    rm nvim-linux64.deb
fi

if [ -d "./nvim" ]; then 
    cp -r ./nvim $HOME/.config
fi
