#!/bin/bash
set -e 
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# ==============================
# Miscellaneous
# ==============================

# Copy over fonts
cp -r $SCRIPT_DIR/../fonts $HOME/.local/share

# Download wallpaper
if ! [ -d "$HOME/Pictures/wallpaper" ]; then
    mkdir $HOME/Pictures/wallpaper
fi

if ! [ -f "$HOME/Pictures/wallpaper/nature.jpg" ]; then
    curl -L --create-dirs https://images.hdqwalls.com/download/tranquility-minimal-4k-6q-2560x1440.jpg > $HOME/Pictures/wallpaper/nature.jpg
fi

# Install Neofetch
if ! [ -x "$(command -v neofetch)" ]; then
    sudo dnf install -y neofetch
    if ! [ -f "$HOME/.bashrc" ]; then
        touch $HOME/.bashrc
    fi
    echo "neofetch" >> $HOME/.bashrc
fi

# ==============================
# Course-specific Dependencies
# ==============================

sudo systemctl disable apport.service
sudo systemctl mask apport.service
sudo apt install -y synaptic
sudo apt install -y dpkg-dev
sudo apt install -y git -y 
sudo apt install -y gitk -y 
sudo apt install -y libncurses5-dev
sudo apt install -y linux-headers-$(uname -r)
sudo apt install -y xorriso
sudo apt install -y iasl
sudo apt install -y fakeroot build-essential xz-utils libssl-dev bc libelf-dev isolinux
sudo apt install -y qemu

# ==============================
# Nvim Dependencies
# ==============================

sudo apt install -y curl
sudo apt install -y build-essential
sudo apt install -y ripgrep

# Install Node.js; needed for certain LSPs used in Nvim
if ! [ -x "$(command -v npm)" ]; then
    curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
    sudo apt-get install -y nodejs
fi

# Install Nvim
if ! [ -x "$(command -v nvim)" ]; then
    curl -fsSLO https://github.com/neovim/neovim/releases/download/v0.8.3/nvim-linux64.deb | sudo -E bash - &&\
    sudo apt install -y ./nvim-linux64.deb
    rm nvim-linux64.deb
fi

# Install Packer.nvim
if ! [ -d "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim" ]; then
    git clone --depth 1 https://github.com/wbthomason/packer.nvim\
     $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim
fi

cp -r $SCRIPT_DIR/../nvim $HOME/.config

# ==============================
# i3 Installation
# ==============================

# Install i3wm-related dependencies
sudo apt install -y rofi
sudo apt install -y i3
sudo apt install -y feh
sudo apt install -y picom

# Install Alacritty
sudo add-apt-repository -y ppa:aslatter/ppa
sudo apt install -y alacritty

# Copy over configuration files
cp -r $SCRIPT_DIR/../rofi $HOME/.config
cp -r $SCRIPT_DIR/../i3 $HOME/.config
cp -r $SCRIPT_DIR/../picom $HOME/.config
cp -r $SCRIPT_DIR/../alacritty $HOME/.config

# Install fonts
NUM_OF_JETBRAINS_FONT=$(fc-list | grep 'ttf: JetBrains Mono' | wc -l)
if [ "$NUM_OF_JETBRAINS_FONT" = "0" ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
fi
